### ISSUE TITLE
[1.12] NullPointerException: TileAccessProxy.onPlayerLogin

### ISSUE THREAD

**Issue by Krutoy242** [shBLOCK/IntegratedProxy#29]
Log in **second time** on dedicated server causing disconnect with error:

```less
[06:43:31] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@789a390a:
java.lang.NullPointerException: null
	at org.cyclops.cyclopscore.datastructure.DimPos.of(DimPos.java:70) ~[DimPos.class:?]
	at com.shblock.integrated_proxy.tileentity.TileAccessProxy.onPlayerLogin(TileAccessProxy.java:405) ~[TileAccessProxy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3468_TileAccessProxy_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
```

It was start to occur after server was updated to new version, but neither `cyclopscore` or `IntegratedProxy` was updated.

First server log in going fine, but second and all other joins are erroring.

Removing `Integrated Proxy` fixes the issue.
(Its strange, because i can connect server even if client have IP and server dont)

### Log
[serverside debug.log with several login attempts](https://github.com/shBLOCK/IntegratedProxy/files/9034178/debug.log)

[serverside debug.log with Integrated Proxy removed, succes connections](https://github.com/shBLOCK/IntegratedProxy/files/9034227/debug.log)

**Comment by shBLOCK** [comment]
This repo is not being maintained anymore, you can use [ForkedProxy](https://www.curseforge.com/minecraft/mc-mods/forked-proxy) for 1.12.2.

**Comment by shBLOCK** [comment]
This repo is not being maintained anymore, you can use [ForkedProxy](https://www.curseforge.com/minecraft/mc-mods/forked-proxy) for 1.12.2.
